# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV['RAILS_ENV'] ||= 'test'

RSpec.configure do |config|
  # BEGIN GENERATED SETTINGS -- These settings are generated by rspec and
  # won't have to be set explicitly in RSpec 4.
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.shared_context_metadata_behavior = :apply_to_host_groups
  # END GENERATED SETTINGS
end

require 'engine_cart'
EngineCart.load_application!
